-- seeds/03_recipes.sql
-- -- recipes seeds
-- INSERT INTO recipes (id, likes, user_id) VALUES (1, 10, 1);
-- INSERT INTO recipes (id, likes, user_id) VALUES (2, 15, 2);
-- INSERT INTO recipes (id, likes, user_id) VALUES (3, 9, 3);
